# Looking at GBIF data (Global Biodiversity Information Facility)

#install.packages("rgbif")
#install.packages("Taxonstand")
#install.packages("CoordinateCleaner")
#install.packages("maps")

library(rgbif)
library(Taxonstand)
library(CoordinateCleaner)
library(maps)
library(dplyr)


# Getting the data -------------------------------------------------------------

species <- "Myrsine coriacea"
?occ_search
occs <- occ_search(scientificName = species,
                   #basisOfRecord = "PRESERVED_SPECIMEN",
                   limit = 100000)
names(occs)
glimpse(occs)

#The occurrences are saved in occs$data. Let’s create a new object from this
#table
myrsine.data <- occs$data
dim(myrsine.data)

#Column names returned from gbif follow the DarwinCore standard
colnames(myrsine.data)

#Exploring raw data
write.csv(myrsine.data,
          "data/raw/myrsine_data.csv",
          row.names = FALSE)


# Checking species taxonomy ----------------------------------------------------

#Let’s check the unique entries for the species name we just searched
sort(unique(myrsine.data$scientificName))

#In this particular case, we have a species with a long history of synonyms.
#In the gbif data, there is already a column showing the currently accepted
#taxonomy:
table(myrsine.data$taxonomicStatus)

#We can also check which of the names are accepted or not:
table(myrsine.data$scientificName, myrsine.data$taxonomicStatus)

#Let’s use the function TPL() from package taxonstand to check if the taxonomic
#updates in the gbif data are correct. This function receives a vector containing
#a list of species and performs both orthographical and nomenclature checking.
#Nomenclature checking follows The Plant List:

#generate a list with unique species names and combine it to the data
species.names <- unique(myrsine.data$scientificName)
dim(species.names)
tax.check <- TPL(species.names)
View(tax.check)

#We will merge the new genus and species and then add them to the original data
# creating new object w/ original and new names after TPL
new.tax <- data.frame(scientificName = species.names,
                      genus.new.TPL = tax.check$New.Genus,
                      species.new.TPL = tax.check$New.Species,
                      status.TPL = tax.check$Taxonomic.status,
                      scientificName.new.TPL = paste(tax.check$New.Genus,
                                                     tax.check$New.Species))
#now we are merging raw data and checked data
myrsine.new.tax <- merge(myrsine.data, new.tax, by = "scientificName")

#Exporting data after taxonomy check
write.csv(myrsine.new.tax,
          "data/processed/data_taxonomy_check.csv",
          row.names = FALSE)


# Checking species's coordinates -----------------------------------------------

plot(decimalLatitude ~ decimalLongitude, data = myrsine.data, asp = 1)
map(, , , add = TRUE) #default: database = "world" #adds a map

#function clean_coordinates(): checks for common errors in coordinates such as
#institutional coordinates, sea coordinates, outliers, zeros, centroids, etc.
#This function does not accept not available information (here addressed as “NA”)
#so we will first select only data that have a numerical value for both latitude
#and longitude
myrsine.coord <- myrsine.data[!is.na(myrsine.data$decimalLatitude)
                              & !is.na(myrsine.data$decimalLongitude),]
dim(myrsine.coord)

#output w/ only potential correct coordinates
geo.clean <- clean_coordinates(x = myrsine.coord,
                               lon = "decimalLongitude",
                               lat = "decimalLatitude",
                               species = "species",
                               value = "clean")

#Let’s plot the output of the clean data
par(mfrow = c(1, 2))
plot(decimalLatitude ~ decimalLongitude, data = myrsine.data, asp = 1)
map(, , , add = TRUE)
plot(decimalLatitude ~ decimalLongitude, data = geo.clean, asp = 1)
map(, , , add = TRUE)

par(mfrow = c(1, 1))

#When setting value = clean it returns only the potentially correct coordinates.
#For checking and reproducibility we want to save all the output with the flags
#generated by the routine. Let’s try a different output.
myrsine.new.geo <- clean_coordinates(x = myrsine.coord,
                                     lon = "decimalLongitude",
                                     lat = "decimalLatitude",
                                     species = "species",
                                     value = "spatialvalid")

#Then, we merge the raw data with the cleaned data.
# merging w/ original data
myrsine.new.geo2 <- merge(myrsine.data, myrsine.new.geo,
                          all.x = TRUE,
                          by = "key")
plot(decimalLatitude ~ decimalLongitude, data = myrsine.new.geo, asp = 1)
map(, , , add = TRUE)

#Exporting the data after coordinate check
write.csv(myrsine.new.geo2,
          "data/processed/myrsine_coordinate_check.csv",
          row.names = FALSE)
